services:

    nginx-proxy:
      container_name: nginx-proxy
      image: jwilder/nginx-proxy
      restart: always
      ports: 
        - "80:80"
        - "443:443"
      volumes: 
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /root/andesiot/letsencrypt/certs:/etc/nginx/certs:ro
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
      labels: 
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  
    letsencrypt:
      container_name: letsencrypt
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      volumes: 
        - /root/andesiot/letsencrypt/certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
      volumes_from: 
        - nginx-proxy:rw
  
    www:
      container_name: nginx
      image: nginx
      restart: always
      expose:
        - "80"
      volumes:
        - /root/andesiot/public_html/andesiot.cl:/usr/share/nginx/html:ro
      environment: 
        - VIRTUAL_HOST=andesiot.cl,www.andesiot.cl
        - LETSENCRYPT_HOST=andesiot.cl,www.andesiot.cl
        - LETSENCRYPT_EMAIL=outfitsoporte@gmail.com
  
    node:
      container_name: node
      image: "node:14"
      #restart: always
      working_dir: /home/node/app
      volumes:
        - ./app/:/home/node/app/
      ports:
        - "3000:3000"
        - "3001:3001"
        - "3002:3002"
  
      links:
        - emqx
        - mongo
  
      command: sh -c "npm run build && npm run start"
  
    mongo:
      container_name: mongo
      image: mongo:4.4
      #restart: always
      environment: 
        TZ: "${TZ}"
        MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
        MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      volumes: 
        - ./mongodata:/data/db 
      ports: 
        - ${MONGO_EXT_PORT}:27017
  
        
    emqx: 
      container_name: emqx
      image: emqx/emqx:4.2.3
      #restart: always
      ports: 
        - 18083:18083
        - 18084:18084
        - 1883:1883
        - 8883:8883
        - 8083:8083
        - 8084:8084
        - 8085:8081
  
      volumes: 
        - vol-emqx-data:/opt/emqx/data
    #    - vol-emqx-etc:/opt/emqx/etc
        - vol-emqx-log:/opt/emqx/log
        - ./letsencrypt/certs/andesiot.cl/:/opt/emqx/etc/certs
  
  
  
      links: 
        - mongo
  
      extra_hosts:
        - "localhost:192.168.1.115"
  
      environment:  
        EMQX_NAME: ANDESIOT
        EMQX_HOST: 127.0.0.1
        TZ: "${TZ}"
  
        EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: etc/certs/key.pem
        EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: etc/certs/fullchain.pem
  
  
        EMQX_LISTENER__WSS__EXTERNAL__KEYFILE: etc/certs/key.pem
        EMQX_LISTENER__WSS__EXTERNAL__CERTFILE: etc/certs/fullchain.pem
  
        # CONTRASEÑA POR DEFECTO
        EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "${EMQX_PASSWORD}"
        EMQX_DASHBOARD__LISTENER__HTTPS__ACCESS__1: allow all
        EMQX_DASHBOARD__LISTENER__HTTPS: 18084
        EMQX_DASHBOARD__LISTENER__HTTPS__ACCEPTORS: 2
        EMQX_DASHBOARD__LISTENER__HTTPS__MAX_CLIENTS: 512
        EMQX_DASHBOARD__LISTENER__HTTPS__KEYFILE: etc/certs/key.pem
        EMQX_DASHBOARD__LISTENER__HTTPS__CERTFILE: etc/certs/fullchain.pem
  
        # 
        EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "${EMQX_APPLICATION_SECRET}"
        
        EMQX_ALLOW_ANONYMOUS: "false"
        EMQX_NOMATCH: "deny"
  
        # CONEXION CON MONGO
        EMQX_AUTH__MONGO__TYPE: single
        EMQX_AUTH__MONGO__SERVER: "mongo:${MONGO_EXT_PORT}"
        EMQX_AUTH__MONGO__POOL: 8
  
        EMQX_AUTH__MONGO__LOGIN: "${MONGO_USERNAME}"
        EMQX_AUTH__MONGO__PASSWORD: "${MONGO_PASSWORD}"
        EMQX_AUTH__MONGO__AUTH_SOURCE: admin
        EMQX_AUTH__MONGO__DATABASE: "andesiot"
        EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxrules"
  
        EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxrules"
        EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
        EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
        EMQX_AUTH__MONGO__SUPER_QUERY: "off"
  
        EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
        EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
        EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"
  
        # Access Control list
  
        EMQX_AUTH__MONGO__ACL_QUERY: "on"
        EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxrules"
        EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"
  
        EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo"
  
        EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
  
  
     
  